# cython: language_level=3
# cython: nonecheck=False
# cython: cdivision=True
# cython: initializedcheck=False
# cython: infer_types=True
# cython: wraparound=False
# cython: boundscheck=False

"""
Auto-generated consolidated functions module.
This file is automatically generated by setup.py and includes all individual
function files in the functions directory.

DO NOT EDIT THIS FILE MANUALLY - it will be overwritten during build.
"""

include "timestamp.pyx"
include "vectors.pyx"
