name: Regression Suite (Mac x86)

on:
  push:
    branches-ignore:
      - main  # Exclude the main branch
      - 'refs/tags/*'  # Exclude tags (releases)

jobs:
  regression_matrix:
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: ['macos-13']
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Python ${{ matrix.python-version }} x64
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
        
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip uv
          python -m uv pip install --upgrade numpy==1.* cython
          python -m uv pip install --upgrade -r $GITHUB_WORKSPACE/tests/requirements.txt
          python -m uv pip install --upgrade -r $GITHUB_WORKSPACE/requirements.txt
          python setup.py build_ext --inplace

      - name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - name: Run Regression Tests
        run: python -m pytest --color=yes
        env:
          GCP_PROJECT_ID: mabeldev
          MYSQL_USER: '${{ secrets.MYSQL_USER }}'
          MYSQL_PASSWORD: '${{ secrets.MYSQL_PASSWORD }}'
          POSTGRES_USER: '${{ secrets.POSTGRES_USER }}'
          POSTGRES_PASSWORD: '${{ secrets.POSTGRES_PASSWORD }}'
          MEMCACHED_SERVER: 'localhost:11211'
          DATA_CATALOG_PROVIDER: 'ICEBERG'
          DATA_CATALOG_CONFIGURATION: '${{ secrets.DATA_CATALOG_CONFIGURATION }}'
          EXPERIMENTAL_EXECUTION_ENGINE: 'true'
