name: Secrets Scanner

on:
  workflow_call

jobs:
  fides:
    name: Fides Secrets Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: fides-scanner
        uses: joocer/fides@main