name: Secrets Scanner

on:
  workflow_call

# Default permissions
permissions:
  contents: read

jobs:
  fides:
    name: Fides Secrets Scanner
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4

      - name: fides-scanner
        uses: joocer/fides@8eb71c29f8561ddadf75e9d0b8071e26e8506ea7  # main